//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsb.UrgentApp.Infrastructure.Db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrgentAppQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrgentAppQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vsb.UrgentApp.Infrastructure.Db.UrgentAppQueries", typeof(UrgentAppQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Patient set Deleted = &apos;{0}&apos; WHERE Id = {1};.
        /// </summary>
        public static string PATIENT_DELETE {
            get {
                return ResourceManager.GetString("PATIENT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Patient(Card_Id, SocialSecurityNumber,FirstName,MiddleName,LastName,BirthDate) VALUES ({0},&apos;{1}&apos;,&apos;{2}&apos;, &apos;{3}&apos;, &apos;{4}&apos;, {5});.
        /// </summary>
        public static string PATIENT_INSERT {
            get {
                return ResourceManager.GetString("PATIENT_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Patient(Card_Id,SocialSecurityNumber,FirstName,MiddleName,LastName,BirthDate,Deleted) VALUES ({0},&apos;{1}&apos;,&apos;{2}&apos;, &apos;{3}&apos;, &apos;{4}&apos;, {5}, &apos;{6}&apos;);.
        /// </summary>
        public static string PATIENT_INSERT_PAST {
            get {
                return ResourceManager.GetString("PATIENT_INSERT_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Patient;.
        /// </summary>
        public static string PATIENT_SELECT {
            get {
                return ResourceManager.GetString("PATIENT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Patient WHERE Card_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string PATIENT_SELECT_BYCARDID {
            get {
                return ResourceManager.GetString("PATIENT_SELECT_BYCARDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Patient WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string PATIENT_SELECT_BYID {
            get {
                return ResourceManager.GetString("PATIENT_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FIRST {0} * FROM Patient WHERE Deleted is not null order by Deleted desc.
        /// </summary>
        public static string PATIENT_SELECT_DELETED {
            get {
                return ResourceManager.GetString("PATIENT_SELECT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  * FROM Patient WHERE Deleted is null.
        /// </summary>
        public static string PATIENT_SELECT_EXCLUDEDELETED {
            get {
                return ResourceManager.GetString("PATIENT_SELECT_EXCLUDEDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Patient set TAG_ID = {0} WHERE Id = {1};.
        /// </summary>
        public static string PATIENT_UPDATE_TAGID {
            get {
                return ResourceManager.GetString("PATIENT_UPDATE_TAGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Room WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string ROOM_SELECT_BYID {
            get {
                return ResourceManager.GetString("ROOM_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Tag WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAG_SELECT_BYID {
            get {
                return ResourceManager.GetString("TAG_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TagEvent (Tag_Id, TagEventType_Id, Created, Patient_Id) VALUES ({0}, {1}, &apos;{2}&apos;, {3});.
        /// </summary>
        public static string TAGEVENT_INSERT {
            get {
                return ResourceManager.GetString("TAGEVENT_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagEvent WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGEVENT_SELECT_BYID {
            get {
                return ResourceManager.GetString("TAGEVENT_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagEvent WHERE patient_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGEVENT_SELECT_BYPATIENTID {
            get {
                return ResourceManager.GetString("TAGEVENT_SELECT_BYPATIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagEvent WHERE tag_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGEVENT_SELECT_BYTAGID {
            get {
                return ResourceManager.GetString("TAGEVENT_SELECT_BYTAGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagEvent WHERE tag_Id = &apos;{0}&apos; and patient_Id = &apos;{1}&apos; and tagEventType_Id = &apos;{2}&apos;;.
        /// </summary>
        public static string TAGEVENT_SELECT_BYTAGID_PATIENTID_TAGEVENTTYPEID {
            get {
                return ResourceManager.GetString("TAGEVENT_SELECT_BYTAGID_PATIENTID_TAGEVENTTYPEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagEventType WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGEVENTTYPE_SELECT_BYID {
            get {
                return ResourceManager.GetString("TAGEVENTTYPE_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagLocation.
        /// </summary>
        public static string TAGLOCATION_SELECT {
            get {
                return ResourceManager.GetString("TAGLOCATION_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TagRegistration WHERE Patient_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGREGISTRATION_DELETE_BYPATIENTID {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_DELETE_BYPATIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TagRegistration(Tag_Id,Patient_Id) VALUES ({0},{1});.
        /// </summary>
        public static string TAGREGISTRATION_INSERT {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagRegistration;.
        /// </summary>
        public static string TAGREGISTRATION_SELECT {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagRegistration WHERE Patient_Id = {0};.
        /// </summary>
        public static string TAGREGISTRATION_SELECT_BYPATIENTID {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_SELECT_BYPATIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagRegistration WHERE Tag_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGREGISTRATION_SELECT_BYTAGID {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_SELECT_BYTAGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM &quot;USER&quot; WHERE NAME = &apos;{0}&apos; and &quot;PASSWORD&quot; = &apos;{1}&apos;;.
        /// </summary>
        public static string USER_SELECT {
            get {
                return ResourceManager.GetString("USER_SELECT", resourceCulture);
            }
        }
    }
}
